### ISSUE TITLE
Request for Review of Zhian's ISC proposal

### ISSUE THREAD

**Issue by zkamvar** [zkamvar/isc-proposal-workbench-2022#4]
Hi @yabellini, Thank you again for speaking with me last week. I believe this proposal is ready for feedback. 

Some particulars that I'm interested in:

 - Narrative: does this flow well? What could be added or removed to improve structure?
 - Roles: are the roles in this project well-described enough or is there something else we should look for?
 - Timeline: Is the bullet-point timeline detailed enough?
 - I was unsure about the "Processes" section and how that would be appropriate for this project since it would be adapting an existing resource.
 - Funding: I am unsure of how much to request. [François' previous ISC proposal (pdf)](https://github.com/zkamvar/isc-proposal-workbench-2022/files/9667045/proposal.pdf) requested $10k USD and the note from Steph Locke's template says that it was a tricky area.

I am comfortable receiving feedback in any way, shape, or form that you are most comfortable with.

The source can be found at https://github.com/zkamvar/isc-proposal-workbench-2022/blob/main/isc-proposal.md#signatories

I also have rendered it to HTML at https://zkamvar.github.io/isc-proposal-workbench-2022#signatories

If you feel more comfortable commenting on a Google Doc, I have uploaded it here with comment access for anyone: https://docs.google.com/document/d/1UtgGs8ekf8p4meVQkKtqhLjOatlrCTrS/edit?usp=sharing&ouid=108016060689021361350&rtpof=true&sd=true

**Comment by yabellini** [comment]
The Narrative flow well. I think the roles and timelines are well described. 
For funding: the hourly rate is 100 dollars and a day is counted as 8 hours.  So that's $800 per day.  Taking into account your timeline, maybe you could request a part of the financing and detail for which part of the timeline you are requesting the financing.
